# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-24 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='spawn_point_id',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
    ]
