# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-24 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_sighting_spawn_point_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='rare',
            field=models.BooleanField(default=True),
        ),
    ]
