# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-24 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_pokemon_rare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='grid',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='user',
        ),
        migrations.AddField(
            model_name='scan',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='step',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='trainer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracker.Trainer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='access_token',
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='api_endpoint',
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
